### ISSUE TITLE
Prev/Next Trip issues

### ISSUE THREAD

**Issue by iMarkeh** [jclgoodwin/bustimes.org#243]
I've got a few issues with the Prev/Next trip buttons. 

Firstly, could it be done so that these move into the same row as the 'close map' button and have this as like a sticky thing so that as you scroll down through the stops, these options remain at the top. It's rather annoying having to always scroll back up to the top. (possibly put a white background behind this and the close map button as currently as you scroll down, the close map button just sits on top of normal text. 
![image](https://github.com/jclgoodwin/bustimes.org/assets/88855038/22c819cd-89ba-4eb0-9575-0a11763470e8)

Secondly, when someone access a trip via the route page (bustimes.org/[route]/vehicles), can the prev/next trip buttons instead be linked to the prev/next buttons on the page rather than prev/next trip the bus did. If I go to a 10:00 trip and click next, it will link me to the 11:30 trip for example as that is the next trip that the bus did. In reality (and in the list), the next trip is at 10:30 (if that makes sense).

Small things but I think they make a big difference to the website.

**Comment by jclgoodwin** [comment]
done

**Comment by iMarkeh** [comment]
The second bit has been done but the first bit is still an issue. 'Close map' still goes over the normal stop text when you scroll down and the next/prev buttons are still right at the top so on some phones and on routes with lots of stops, you can be scrolling forever to get to the next/prev buttons.
